export type LiteratureRecord = {
  id: string;
  title: string;
  year: number;
  journal: string;
  compound: string;
  biologicalModel: string;
  assay: string;
  finding: string;
  pmid: string;
  url: string;
  evidenceLevel: "direct" | "supporting" | "method";
  access: "PubMed" | "Open access";
};

export const literatureRecords: LiteratureRecord[] = [
  {
    id: "LIT-001",
    title: "Apigenin inhibits cell proliferation, migration, and invasion by targeting Akt in the A549 human lung cancer cell line",
    year: 2017,
    journal: "Oncology Letters",
    compound: "Apigenin",
    biologicalModel: "A549 NSCLC cells",
    assay: "MTT, colony formation, migration and invasion",
    finding: "Reported dose- and time-dependent antiproliferative effects with PI3K/Akt pathway observations.",
    pmid: "28125432",
    url: "https://pubmed.ncbi.nlm.nih.gov/28125432/",
    evidenceLevel: "direct",
    access: "PubMed",
  },
  {
    id: "LIT-002",
    title: "Quercetin induces pro-apoptotic autophagy via SIRT1/AMPK signaling pathway in human lung cancer cell lines A549 and H1299 in vitro",
    year: 2021,
    journal: "Thoracic Cancer",
    compound: "Quercetin",
    biologicalModel: "A549 and H1299 cells",
    assay: "CCK-8, apoptosis, western blot and microscopy",
    finding: "Reported dose-dependent viability reduction and autophagy-associated apoptosis in vitro.",
    pmid: "33709560",
    url: "https://pubmed.ncbi.nlm.nih.gov/33709560/",
    evidenceLevel: "direct",
    access: "Open access",
  },
  {
    id: "LIT-003",
    title: "Curcumin inhibits the development of non-small cell lung cancer by inhibiting autophagy and apoptosis",
    year: 2018,
    journal: "Experimental and Therapeutic Medicine",
    compound: "Curcumin",
    biologicalModel: "A549 and H1299 cells",
    assay: "Viability, colony formation, apoptosis and autophagy",
    finding: "Reported time- and dose-dependent viability effects with mTOR-pathway observations.",
    pmid: "29201217",
    url: "https://pubmed.ncbi.nlm.nih.gov/29201217/",
    evidenceLevel: "direct",
    access: "Open access",
  },
  {
    id: "LIT-004",
    title: "Curcumin and quercetin synergistically inhibit cancer cell proliferation in multiple cancer cells",
    year: 2019,
    journal: "Phytomedicine",
    compound: "Curcumin + quercetin",
    biologicalModel: "A549 and other cancer cell lines",
    assay: "Cell proliferation and combination analysis",
    finding: "Reported combination effects; cross-study use requires matching concentration, duration and assay context.",
    pmid: "30599890",
    url: "https://pubmed.ncbi.nlm.nih.gov/30599890/",
    evidenceLevel: "supporting",
    access: "PubMed",
  },
  {
    id: "LIT-005",
    title: "Identification of epigallocatechin-3-gallate as a potent inducer of p53-dependent apoptosis in A549",
    year: 2009,
    journal: "Cancer Letters",
    compound: "EGCG / catechin family",
    biologicalModel: "A549 cells",
    assay: "Viability, caspase 3/7 and reporter assays",
    finding: "Reported p53-dependent apoptosis for EGCG while distinguishing it from a catechin mixture.",
    pmid: "19406223",
    url: "https://pubmed.ncbi.nlm.nih.gov/19406223/",
    evidenceLevel: "supporting",
    access: "PubMed",
  },
  {
    id: "LIT-006",
    title: "Green tea catechin EGCG attenuates viability of A549 cells via reducing Bcl-xL expression",
    year: 2014,
    journal: "Experimental and Therapeutic Medicine",
    compound: "EGCG",
    biologicalModel: "A549 cells",
    assay: "MTT and gene-expression analysis",
    finding: "Reported dose-dependent proliferation reduction between 3 and 100 µM in the stated in-vitro context.",
    pmid: "24944597",
    url: "https://pubmed.ncbi.nlm.nih.gov/24944597/",
    evidenceLevel: "supporting",
    access: "Open access",
  },
  {
    id: "LIT-007",
    title: "Butein and Frondoside-A combination exhibits additive anti-cancer effects on tumor cell viability",
    year: 2022,
    journal: "International Journal of Molecular Sciences",
    compound: "Butein + Frondoside-A",
    biologicalModel: "A549 and MDA-MB-231 cells",
    assay: "CellTiter-Glo, colony growth and invasion",
    finding: "Provides a directly relevant CellTiter-Glo assay-method example with repeated experiments.",
    pmid: "35008855",
    url: "https://pubmed.ncbi.nlm.nih.gov/35008855/",
    evidenceLevel: "method",
    access: "Open access",
  },
  {
    id: "LIT-008",
    title: "RNAi screening identifies KAT8 as a key molecule important for cancer cell survival",
    year: 2013,
    journal: "International Journal of Oncology",
    compound: "RNAi perturbations",
    biologicalModel: "A549 cells in 96-well plates",
    assay: "CellTiter-Glo after five-day perturbation",
    finding: "Method reference for plate-based A549 viability screening with positive and negative controls.",
    pmid: "23638218",
    url: "https://pubmed.ncbi.nlm.nih.gov/23638218/",
    evidenceLevel: "method",
    access: "PubMed",
  },
  {
    id: "LIT-009",
    title: "A novel small molecule, Rosline, inhibits growth and induces caspase-dependent apoptosis in A549",
    year: 2016,
    journal: "Cell Biology International",
    compound: "Rosline",
    biologicalModel: "A549 cells",
    assay: "Library screen, viability and apoptosis",
    finding: "Reported an A549 screening hit and subsequent mechanistic validation; not a clinical result.",
    pmid: "27006094",
    url: "https://pubmed.ncbi.nlm.nih.gov/27006094/",
    evidenceLevel: "supporting",
    access: "PubMed",
  },
  {
    id: "LIT-010",
    title: "Quercetin suppresses lung cancer growth by targeting Aurora B kinase",
    year: 2016,
    journal: "Oncotarget",
    compound: "Quercetin",
    biologicalModel: "A549 cells and an A549 xenograft model",
    assay: "Kinase, cellular and in-vivo studies",
    finding: "Mechanistic evidence connected quercetin exposure with Aurora B activity; translation remains unproven.",
    pmid: "27704720",
    url: "https://pubmed.ncbi.nlm.nih.gov/27704720/",
    evidenceLevel: "supporting",
    access: "Open access",
  },
  {
    id: "LIT-011",
    title: "Sesamin induces A549 cell mitophagy and mitochondrial apoptosis via reactive oxygen species",
    year: 2020,
    journal: "International Journal of Molecular Medicine",
    compound: "Sesamin",
    biologicalModel: "A549 cells",
    assay: "CCK-8, migration, cell cycle and flow cytometry",
    finding: "Reported viability and migration effects together with mitochondrial and apoptosis measurements.",
    pmid: "32392913",
    url: "https://pubmed.ncbi.nlm.nih.gov/32392913/",
    evidenceLevel: "direct",
    access: "Open access",
  },
  {
    id: "LIT-012",
    title: "Zebularine inhibits the growth of A549 lung cancer cells via cell cycle arrest and apoptosis",
    year: 2013,
    journal: "Molecular Carcinogenesis",
    compound: "Zebularine",
    biologicalModel: "A549 and normal pulmonary fibroblasts",
    assay: "Growth, cell cycle, apoptosis and ROS",
    finding: "Reported an approximately 70 µM IC50 at 72 hours for A549 in the study-specific context.",
    pmid: "23661569",
    url: "https://pubmed.ncbi.nlm.nih.gov/23661569/",
    evidenceLevel: "direct",
    access: "PubMed",
  },
];

export const evidenceSources = [
  ["PubChem", "Chemical identity and public properties", "Registered adapter"],
  ["ChEMBL", "Bioactivity, targets and assay context", "Registered adapter"],
  ["PubMed / PMC", "Paper metadata and lawful open-access links", "Curated evidence"],
  ["NCI-60 / CellMiner", "Cancer-cell-line response matrices", "Bulk connector"],
  ["TDC", "Drug-discovery benchmark datasets", "PyTDC connector"],
  ["Tox21 / ToxCast", "Endpoint-specific toxicology", "Bulk connectors"],
  ["COCONUT / NPASS / LOTUS", "Natural-product identity and occurrence", "Bulk connectors"],
  ["ANPDB", "African compounds, organisms and literature", "Bulk connector"],
  ["UniProt", "Protein identity and sequence", "REST connector"],
  ["Chemspace", "Supplier and availability search", "API-key connector"],
] as const;
