"use client";

import { useMemo, useState } from "react";

type TrackStatus = "built" | "free-build" | "free-heavy" | "funding";
type Track = {
  priority: string;
  capability: string;
  recursion: string;
  osiel: string;
  alternative: string;
  status: TrackStatus;
  action: string;
  proof: string;
};

const tracks: Track[] = [
  { priority:"P0", capability:"Workflow orchestration", recursion:"LOWE coordinates target, chemistry and experiments across proprietary tools.", osiel:"Ten-stage Open Discovery trace with typed APIs, evidence IDs and review gate.", alternative:"FastAPI + Next.js + explicit state machine", status:"built", action:"Keep extending adapters behind the same trace contract.", proof:"Open Discovery run persists ten ordered stages." },
  { priority:"P0", capability:"Chemical identity", recursion:"Enterprise compound identity and internal chemical data systems.", osiel:"RDKit parent standardization, InChIKey, descriptors, deduplication and flags.", alternative:"RDKit + versioned source registry", status:"built", action:"Freeze standardization versions and add release-level identity tests.", proof:"192 packaged structures plus live ChEMBL records compute locally." },
  { priority:"P0", capability:"Public scientific evidence", recursion:"Public evidence plus proprietary maps and internal experimental history.", osiel:"Open Targets, PubChem, ChEMBL, RCSB and AlphaFold clients with provenance.", alternative:"Official public APIs and governed bulk releases", status:"built", action:"Add caching, rate limits and release snapshots before shared use.", proof:"Live EGFR check resolved target, PDB 4WKQ and ChEMBL analogues." },
  { priority:"P0", capability:"Docking", recursion:"Multiple proprietary and internal predictive engines; docking is one supporting method.", osiel:"Real Vina 1.2.7 worker, immutable inputs/outputs, downloadable poses and a heavy-atom redocking RMSD gate.", alternative:"AutoDock Vina + reviewed PDBQT preparation", status:"built", action:"Expand the single-complex RMSD gate into a target-family redocking and decoy-enrichment suite.", proof:"Official 1IEP example completes without a simulated score; redocking remains distinct from affinity validation." },
  { priority:"P0", capability:"Audit and claim control", recursion:"Enterprise lineage, internal governance and human review.", osiel:"Audit ledger, checksums, simulation barriers, model promotion gates and claim boundaries.", alternative:"SQLite reference; PostgreSQL/RLS production target", status:"built", action:"Move append-only records to authenticated PostgreSQL and object lock.", proof:"Simulation is permanently rejected from training eligibility." },
  { priority:"P0", capability:"Experiment software loop", recursion:"Robotic scheduling and real high-throughput measurements.", osiel:"Protocol, plate map, deterministic dry-run, QC, failure reasons and next-candidate logic.", alternative:"Open-source LIMS/ELN adapter plus qualified instrument parsers", status:"built", action:"Keep simulation for teaching; connect one real plate reader only after SOP approval.", proof:"72-row dose-response dry-run and QC gates pass automated tests." },
  { priority:"P1", capability:"Scientific Professor / RAG", recursion:"LLM orchestration over large proprietary scientific context.", osiel:"Opt-in Qwen3-8B/Ollama composer over bounded retrieved evidence, valid-ID citations, abstention, injection screen and deterministic fallback.", alternative:"Expand the current adapter with a versioned faculty library and page-level chunks", status:"built", action:"Load approved documents, add retrieval evaluations and require faculty correction before shared teaching use.", proof:"The software path runs locally; answer quality and scientific validation are still external gates." },
  { priority:"P1", capability:"Bulk public bioactivity data", recursion:"Large cleaned internal datasets accumulated through experiments and partnerships.", osiel:"Immutable bounded ChEMBL endpoint snapshots now preserve raw/normalized checksums, exact relation, thresholds, conflicts, duplicates and scaffolds.", alternative:"Extend the same manifest to approved bulk ChEMBL, PubChem BioAssay, NCI-60/CellMiner and TDC releases", status:"built", action:"Add release-level bulk import and independent assay curation without mixing endpoints.", proof:"The runnable pipeline is built; its scientific value still depends on the chosen task and source quality." },
  { priority:"P1", capability:"Baseline target/activity models", recursion:"MatchMaker and other validated proprietary interaction models.", osiel:"ECFP4 logistic baseline with separate scaffold train, calibration and frozen test partitions, calibration metrics and applicability domain.", alternative:"Compare the built baseline with Chemprop only after the same split is frozen", status:"built", action:"Run one approved endpoint, publish a model card and add a locked external dataset before considering promotion.", proof:"Training/evaluation is executable; prospective validity and Recursion-scale proprietary performance are not claimed." },
  { priority:"P1", capability:"ADMET prediction", recursion:"Integrated internal and partner models plus experimental feedback.", osiel:"Transparent rule panel, not calibrated prediction.", alternative:"ADMET-AI and TDC endpoint datasets", status:"free-build", action:"Add isolated versioned adapter, then validate each endpoint and applicability domain.", proof:"Integration is free; trustworthy performance needs approved task-specific evaluation." },
  { priority:"P1", capability:"Billion-scale analogue search", recursion:"MatchMaker searches enormous make-on-demand chemical spaces with a proprietary target-interaction model.", osiel:"Real bounded SmallWorld search of the provider-reported 10.10B-entry REALDB map, followed by local RDKit triage.", alternative:"Keep using public remote indexes; never attempt to store or dock billions locally", status:"built", action:"Add provider-cache policy and a second public-map benchmark; keep target activity claims blocked.", proof:"A live aspirin run returned and assessed 24 structures from 9.43B mapped entries; this is structural search, not MatchMaker." },
  { priority:"P1", capability:"Workflow workers", recursion:"Large distributed compute and laboratory scheduling platform.", osiel:"Synchronous reference API with process-bounded Vina only.", alternative:"Prefect or Celery + Redis/PostgreSQL + local GPU worker", status:"free-build", action:"Queue long jobs, add cancellation, quotas, retries and heartbeat state.", proof:"Open-source software is free and can run on the current workstation at small scale." },
  { priority:"P2", capability:"Public phenomics starter", recursion:"Massive internally generated phenotypic maps across perturbations.", osiel:"No image-phenomics dataset or model.", alternative:"JUMP-Cell Painting public data + CellProfiler + DINOv2/ViT embeddings", status:"free-heavy", action:"Start with a small public subset, reproduce one benchmark and link image embeddings to perturbations.", proof:"Data/software can be free; downloads, storage and GPU training are substantial." },
  { priority:"P2", capability:"Generative chemistry research", recursion:"Integrated generative lead-optimization models with experimental feedback.", osiel:"Absent by policy.", alternative:"REINVENT, DrugEx or graph generators with RDKit/SA constraints", status:"free-heavy", action:"Only enable after validated scoring objectives, novelty/IP checks and medicinal-chemist review.", proof:"Generating SMILES is free; generating useful, synthesizable and novel leads is not proven by software alone." },
  { priority:"P2", capability:"Active learning", recursion:"Measured results continuously improve models and experiment selection.", osiel:"Uncertainty, distance-to-training and fingerprint diversity now produce an auditable next-test proposal; execution and promotion remain blocked.", alternative:"Connect approved measured results to the existing immutable snapshot and challenger gates", status:"built", action:"Use proposals only after assay feasibility, compound availability and supervisor approval; then compare information gain prospectively.", proof:"The selection algorithm is built; learning value still requires genuine measured experiments." },
  { priority:"P3", capability:"Proprietary phenomic map", recursion:"Years of standardized in-house imaging and perturbation experiments.", osiel:"None.", alternative:"Public JUMP-CP is a research substitute, not an equivalent private map.", status:"funding", action:"PAUSED: requires laboratory capacity, staff, plates, cells, reagents, imaging and quality systems.", proof:"ChatGPT cannot create measured cellular phenotypes." },
  { priority:"P3", capability:"Robotic laboratory", recursion:"Automated compound storage, liquid handling, assay execution and readers.", osiel:"Simulation and parser contracts only.", alternative:"University core facility or external CRO before buying robots", status:"funding", action:"PAUSED: seek an institutional partnership; do not purchase hardware first.", proof:"Physical instruments, calibration, maintenance and consumables require funding." },
  { priority:"P3", capability:"Compounds and synthesis", recursion:"Supplier partnerships, compound libraries and physical make-on-demand execution.", osiel:"Search and procurement hand-off only.", alternative:"Test a very small approved set through university inventory/collaboration", status:"funding", action:"PAUSED: compounds, shipping, customs, analytical QC and synthesis cost money.", proof:"A database record cannot substitute for a vial with verified identity and purity." },
  { priority:"P3", capability:"Prospective validation", recursion:"Large repeated experimental programmes and internal validation history.", osiel:"No prospective measured validation.", alternative:"One supervised university assay with preregistered controls", status:"funding", action:"PAUSED until a partner supplies cells, reagents, instruments and scientific supervision.", proof:"Software tests cannot establish biological performance." },
  { priority:"P3", capability:"Million-user infrastructure", recursion:"Enterprise platform, compute fleet, security and support organisation.", osiel:"Single-workspace research showcase.", alternative:"Start one lab/one university; scale only after usage is proven", status:"funding", action:"PAUSED: do not optimize for one million users before a validated research workflow exists.", proof:"Hosting, GPU capacity, SRE, support, security and compliance require recurring budget." },
  { priority:"P3", capability:"IP, legal and regulated operations", recursion:"Large legal, privacy, safety, quality and IP functions.", osiel:"Technical claim boundaries and licence notes only.", alternative:"University technology-transfer, ethics, biosafety and legal offices", status:"funding", action:"PAUSED as an internal function; use institutional partners and do not make clinical claims.", proof:"ChatGPT cannot grant licences, freedom-to-operate, ethics approval or institutional acceptance." },
];

const statusCopy: Record<TrackStatus, { label:string; note:string }> = {
  built:{ label:"Built now", note:"Implemented and software-tested" },
  "free-build":{ label:"Free build", note:"ChatGPT/code can implement; external validation remains" },
  "free-heavy":{ label:"Free but heavy", note:"No licence fee assumed; needs data, storage, compute and curation" },
  funding:{ label:"Funding required", note:"Paused—physical, proprietary or operating resources required" },
};

export function RecursionRoadmap() {
  const [filter,setFilter] = useState<"all" | TrackStatus>("all");
  const [focus,setFocus] = useState(tracks[0].capability);
  const visible = useMemo(() => tracks.filter((track) => filter === "all" || track.status === filter),[filter]);
  const selected = tracks.find((track) => track.capability === focus) ?? visible[0] ?? tracks[0];
  const counts = Object.fromEntries((Object.keys(statusCopy) as TrackStatus[]).map((status) => [status,tracks.filter((track) => track.status === status).length])) as Record<TrackStatus,number>;
  return <>
    <section className="module-heading"><div><span>STRATEGY / CAPABILITY GAP</span><h1>What Recursion has that OSIEL does not</h1><p>A priority-ordered, no-hype build map separating software ChatGPT can implement, free-but-heavy research work, and capabilities that genuinely require funding.</p></div></section>
    <div className="roadmap-rule"><b>Operating rule</b><span>Build every credible open-source software layer first. Pause physical, proprietary, high-scale and institutional claims until funding or a university partner exists.</span></div>
    <div className="roadmap-stats">{(Object.keys(statusCopy) as TrackStatus[]).map((status) => <button key={status} onClick={() => setFilter(filter === status ? "all" : status)} className={`${status} ${filter === status ? "active" : ""}`}><span>{statusCopy[status].label}</span><strong>{counts[status]}</strong><small>{statusCopy[status].note}</small></button>)}</div>
    <div className="roadmap-layout">
      <article className="module-card roadmap-ledger"><div className="card-title"><div><span>PRIORITY LEDGER</span><h2>{visible.length} capability workstreams</h2></div><select value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)}><option value="all">All workstreams</option>{(Object.keys(statusCopy) as TrackStatus[]).map((status) => <option value={status} key={status}>{statusCopy[status].label}</option>)}</select></div><div className="roadmap-list">{visible.map((track) => <button key={track.capability} className={`${track.status} ${selected.capability === track.capability ? "active" : ""}`} onClick={() => setFocus(track.capability)}><i>{track.priority}</i><span><b>{track.capability}</b><small>{track.osiel}</small></span><em>{statusCopy[track.status].label}</em></button>)}</div></article>
      <aside className={`module-card roadmap-detail ${selected.status}`}><div className="roadmap-detail-head"><span>{selected.priority} · {statusCopy[selected.status].label}</span><h2>{selected.capability}</h2></div><section><span>WHAT RECURSION HAS</span><p>{selected.recursion}</p></section><section><span>WHAT OSIEL HAS</span><p>{selected.osiel}</p></section><section><span>NO-COST / LOWER-COST ALTERNATIVE</span><p>{selected.alternative}</p></section><section className="roadmap-action"><span>NEXT DECISION</span><p>{selected.action}</p></section><div className="roadmap-proof"><b>Reality check</b><span>{selected.proof}</span></div></aside>
    </div>
    <section className="module-card roadmap-sequence"><div className="card-title"><div><span>EXECUTION ORDER</span><h2>Closest credible path with almost no budget</h2></div><b>Do not skip scientific gates</b></div><ol>{[
      ["NOW","Stabilize software","Public evidence, RDKit, Vina, provenance, local deployment and reproducible tests."],
      ["NEXT","Run one approved model task","Use the built ChEMBL snapshot and scaffold-safe baseline on one frozen endpoint, then publish its failures."],
      ["THEN","Expand professor retrieval","Load faculty-approved, versioned documents with page citations; never use the LLM as the scientific predictor."],
      ["AFTER","Public phenomics subset","Reproduce one JUMP-CP benchmark on a manageable subset and publish limitations."],
      ["PARTNER","One real assay","Ask a university lab to run a small preregistered study with controls and raw-data return."],
      ["ONLY THEN","Scale or fundraise","Use measured reproducibility and prospective value—not UI features—as the funding proof."],
    ].map(([when,title,detail],index) => <li key={title}><i>{index+1}</i><span>{when}</span><div><b>{title}</b><small>{detail}</small></div></li>)}</ol></section>
    <div className="roadmap-bottom"><b>Bottom line:</b> free tools can reproduce much of the orchestration and educational workflow. They cannot reproduce Recursion’s proprietary data advantage, industrial wet lab, physical compound access, prospective evidence, or operating scale.</div>
  </>;
}
